credentials:
  usernames:
    admin:
      name: Administrator
      password: admin123
    phuc:
      name: Lê Hoàng Phúc
      password: phuc2025
cookie:
  name: rma_app_cookie
  key: supersecretkey123
  expiry_days: 1
preauthorized:
  emails: []
